import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Button } from "../components/Button";
import { Navbar } from "../components/Navbar";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Funktion</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="grid grid-cols-4 w-screen h-screen home">
				<div className="col-span-3 h-full">
					<Navbar transparent={true} />
					<div className="px-28 h-full flex justify-center flex-col space-y-10">
						<div className="space-y-6">
							<h1 className="text-6xl font-bold pr-20">Productivity at its finest</h1>
							<p>Funktion is the best way to organize your simple tasks during the day</p>
						</div>
						<div className="flex space-x-4 items-center w-full">
							<Link href="/register">
								<a>
									<Button color="black" className="">
										Get Started
									</Button>
								</a>
							</Link>
							<Link href="/login">
								<a className="font-semibold hover:opacity-80">or Login</a>
							</Link>
						</div>
					</div>
				</div>
				<div className="w-full col-span-1 h-full relative">
					<Image
						src="https://images.unsplash.com/photo-1579547621113-e4bb2a19bdd6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=584&q=80"
						alt="Gradient"
						layout="fill"
						objectFit="cover"
						className="grayscale-image"
					/>
				</div>
			</div>
		</div>
	);
};

export default Home;
